mysql:
  image: mysql/mysql-server:5.6
  ports: 
  - "80:80"
  environment:
  - MYSQL_ROOT_PASSWORD=123456
  volumes:
  - ~/.dolia-workspace/modules/lnmp/mysql-data:/var/lib/mysql
  ports:
  - "3306:3306"
web:
  build: .
  dockerfile: Dockerfile
  ports:
  - "80:80"
  links:
  - mysql:mysql-server
  volumes:
  - ~/.dolia-workspace/modules/lnmp/nginx/sites-enabled:/etc/nginx/sites-enabled
  - ~/code:/share
